### ISSUE TITLE
Kite doesn't detect VSCodium and VSCodium extension doesn't detect Kite Engine

### ISSUE THREAD

**Issue by DaCurse** [kiteco/vscode-plugin#298]
I'm using VSCodium and have the Kite extension installed, I have also installed Kite Engine and it doesn't detect VSCodium as VSCode.

**Comment by axeII** [comment]
Strange I was able to install kite and extension manually for VSCodium and it's working for me fine. 
**Although** it would be great to have official support by adding package to https://open-vsx.org which is used by VSCodium. 

Btw there is a thread in main kite repository for supporting VSCodium https://github.com/kiteco/issue-tracker/issues/224.

**Comment by tywmick** [comment]
There's currently no legal way to install and use Kite's VS Code plugin with VSCodium, as far as I can tell.

1. Visual Studio Marketplace's [Terms of Use](https://aka.ms/vsmarketplace-ToU) requires that the Marketplace and any extensions it distributes only be used with Microsoft products. This seems to rule out both of the following:
    - [Connecting VSCodium to VS Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) (though one VS Code maintainer at Microsoft [thinks it's fine](https://github.com/Microsoft/vscode/issues/1557#issuecomment-173449135))
    - Downloading the `.vsix` directly from [the VS Marketplace website](https://marketplace.visualstudio.com/items?itemName=kiteco.kite) and installing it manually
2. The [license](https://github.com/kiteco/vscode-plugin/blob/master/LICENSE) of Kite's VS Code plugin requires obtaining written permission before reproducing it, so that seems to rule out cloning the repository and building it yourself.

Not that I think doing any of those things is _wrong_, per se, just not _legal_. All else being equal, legal would be nicer. [Publishing to Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) or adding the compiled `.vsix` to the plugin's [GitHub Releases](https://github.com/kiteco/vscode-plugin/releases) would fix that.

**Comment by edzkite** [comment]
We're now on Open VSX: https://open-vsx.org/extension/kiteco/kite
