### ISSUE TITLE
VS Code whitelisting defaults to C:\, not C:\Users\<user> like other editors

### ISSUE THREAD

**Issue by jlozano** [kiteco/vscode-plugin#35]
This is for both adding to whitelist and suppressed list (by pressing cancel on the prompt)

Reported by @keien.

Are we using the `clientapi/projectdir` endpoint like we do in atom?

**Comment by abe33** [comment]
Yes, it's basically the same logic: 

- calling `/clientapi/projectdir` with the current file name
- if `200` -> show the resulting path to whitelist
- if `404` -> fallback to either the current VSCode root path (https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace) or `os.homedir()`, this part is the same as in Atom as well. In Atom we're looking for the project path then fall back to `os.homedir()`
- if `403` -> show nothing as the notification have been suppressed

I'll take a look at that.

**Comment by abe33** [comment]
So, it appears to be related to the fact that drive letters appear as lower case in VSCode, on my win7 device, A file in a git repo on a `D:` drive was proposed the proper path to whitelist, on the `C:` drive, for a file outside a git repo, the fact that I was sending `c:\...` instead of `C:\...` seems to make kited miss the home directory. I've pushed a patch to force drive letters to be uppercased when sent to `kited` and it solves that issue.
