### ISSUE TITLE
Got "Kite Install" tab when I've always been logged in

### ISSUE THREAD

**Issue by adamsmith** [kiteco/vscode-plugin#87]
I had VS Code open for a long time, and this came up.

Maybe it was triggered by a Kite update?  (Pure speculation)

When I clicked on 'Continue' I just got a giant Kite logo.

![screen shot 2018-02-08 at 9 57 01 am](https://user-images.githubusercontent.com/87728/35989670-a57247c6-0cb6-11e8-8a36-bc38c1ca9a33.png)

**Comment by dbratz1177** [comment]
@adamsmith if you can remember, on the the screen with the 'giant Kite logo', was there anything else?

**Comment by adamsmith** [comment]
I don't recall there being any obvious text, but I'm not sure I looked closely.  The logo was truly giant so might have grabbed all of my attention.

I now seem instead to be getting a "you need to login" notification in VS Code when Kite updates are installed, which leads to a form that looks like this (below), so maybe the install + giant logo thing was fixed?

![screen shot 2018-02-21 at 1 32 55 pm](https://user-images.githubusercontent.com/87728/36506516-c06c441e-170b-11e8-93e2-83ad8fbb2c7a.png)

**Comment by dbratz1177** [comment]
Thanks for the additional info. Based on my digging up to this point, my gut's leaning towards these issues (and other similar ones) being all somehow connected, perhaps through the kite-installer package

**Comment by adamsmith** [comment]
Cool, makes sense to me!

**Comment by adamsmith** [comment]
May also be related: https://github.com/kiteco/atom-plugin/issues/310#issuecomment-366755735

**Comment by dbratz1177** [comment]
I'm wondering how long you had VSCode open - #56 updated the `kite-installer` package to a significantly changed version, and I'm wondering if there was some sort of weird legacy type interactions happening there.
Seeing as the plugin for atom still has yet to update it's kite-installer package (there's currently kiteco/atom-plugin/pull/317 in the works for that), this gets me wondering if kiteco/atom-plugin#310 and this might be due to the same underlying (and possibly legacy) thing

**Comment by adamsmith** [comment]
Interesting!

It very well could have been a legacy thing.  I just updated VS Code and the plugin and will keep an eye out.
